# - algorithm: RSA
#   runner: RSA
#   variants:
#     - "2048"
#     - "4096"
- algorithm: Saber
  runner: OQS
  variants:
    - LightSaber-KEM
    - Saber-KEM
    - FireSaber-KEM
- algorithm: HQC
  runner: OQS
  variants:
    - HQC-128
    - HQC-192
    - HQC-256
- algorithm: Classic-McEliece
  runner: OQS
  variants: 
    - Classic-McEliece-348864
    - Classic-McEliece-348864f
    - Classic-McEliece-460896
    - Classic-McEliece-460896f
    - Classic-McEliece-6688128
    - Classic-McEliece-6688128f
    - Classic-McEliece-6960119
    - Classic-McEliece-6960119f
    - Classic-McEliece-8192128
    - Classic-McEliece-8192128f
- algorithm: BIKE1
  runner: OQS
  variants: 
    - BIKE1-L1-CPA
    - BIKE1-L3-CPA
    - BIKE1-L1-FO
    - BIKE1-L3-FO
- algorithm: NTRU-HPS
  runner: OQS
  variants:
    - NTRU-HPS-2048-509
    - NTRU-HPS-2048-677
    - NTRU-HPS-4096-821
- algorithm: NTRU-HRSS
  runner: OQS
  variants:
    - NTRU-HRSS-701
- algorithm: FrodoKEM
  runner: OQS
  variants: 
    - FrodoKEM-640-AES
    - FrodoKEM-640-SHAKE
    - FrodoKEM-976-AES
    - FrodoKEM-976-SHAKE
    - FrodoKEM-1344-AES
    - FrodoKEM-1344-SHAKE
- algorithm: CRYSTALS-Kyber
  runner: OQS
  variants:
    - Kyber512
    - Kyber768
    - Kyber1024
    - Kyber512-90s
    - Kyber768-90s
    - Kyber1024-90s
- algorithm: SIKE
  runner: OQS
  variants:
    - SIKE-p434
    - SIKE-p503
    - SIKE-p610
    - SIKE-p751
    - SIKE-p434-compressed
    - SIKE-p503-compressed
    - SIKE-p610-compressed
    - SIKE-p751-compressed
- algorithm: NTRU Prime
  runner: OQS
  variants:
    - ntrulpr653
    - ntrulpr761
    - ntrulpr857
    - sntrup653
    - sntrup761
    - sntrup857
# - algorithm: EDCH
#   runner: ECC
#   variants:
#     - P-192
#     - P-224
#     - P-256
#     - P-384
